In [3]:
import pandas as pd
df = pd.read_csv("../raw_data/Telco-Customer-Churn.csv")
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [4]:
df.describe()

       SeniorCitizen       tenure  MonthlyCharges
count    7043.000000  7043.000000     7043.000000
mean        0.162147    32.371149       64.761692
std         0.368612    24.559481       30.090047
min         0.000000     0.000000       18.250000
25%         0.000000     9.000000       35.500000
50%         0.000000    29.000000       70.350000
75%         0.000000    55.000000       89.850000
max         1.000000    72.000000      118.750000

In [5]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7043 non-null   str
 1   gender            7043 non-null   str
 2   SeniorCitizen     7043 non-null   int64
 3   Partner           7043 non-null   str
 4   Dependents        7043 non-null   str
 5   tenure            7043 non-null   int64
 6   PhoneService      7043 non-null   str
 7   MultipleLines     7043 non-null   str
 8   InternetService   7043 non-null   str
 9   OnlineSecurity    7043 non-null   str
 10  OnlineBackup      7043 non-null   str
 11  DeviceProtection  7043 non-null   str
 12  TechSupport       7043 non-null   str
 13  StreamingTV       7043 non-null   str
 14  StreamingMovies   7043 non-null   str
 15  Contract          7043 non-null   str
 16  PaperlessBilling  7043 non-null   str
 17  PaymentMethod     7043 non-null   str
 18  MonthlyCharges    7043 non-null   float64
 19  TotalCharges      7043 non-null   str
 20  Churn             7043 non-null   str
dtypes: float64(1), int64(2), str(18)
memory usage: 1.1 MB

In [6]:
df.isnull().sum()

customerID          0
gender              0
SeniorCitizen       0
Partner             0
Dependents          0
tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
MonthlyCharges      0
TotalCharges        0
Churn               0
dtype: int64

In [7]:
df.duplicated().sum()

np.int64(0)

In [8]:
df["TotalCharges"].value_counts().head(10)

TotalCharges
20.2     11
         11
19.75     9
19.9      8
20.05     8
19.65     8
45.3      7
19.55     7
20.15     6
19.45     6
Name: count, dtype: int64

In [9]:
(df["TotalCharges"].str.strip() == "").sum()

np.int64(11)

In [10]:
df["TotalCharges"] = pd.to_numeric(df["TotalCharges"], errors="coerce")

df["TotalCharges"].isnull().sum()

np.int64(11)

In [11]:
df[df["TotalCharges"].isnull()][["tenure", "MonthlyCharges", "TotalCharges"]]

      tenure  MonthlyCharges  TotalCharges
488        0           52.55           NaN
753        0           20.25           NaN
936        0           80.85           NaN
1082       0           25.75           NaN
1340       0           56.05           NaN
3331       0           19.85           NaN
3826       0           25.35           NaN
4380       0           20.00           NaN
5218       0           19.70           NaN
6670       0           73.35           NaN
6754       0           61.90           NaN

In [12]:
df = df.dropna(subset=["TotalCharges"]).copy()
df.shape

(7032, 21)

In [13]:
df.isnull().sum().sum()

np.int64(0)

In [14]:
df["Churn"].value_counts()

Churn
No     5163
Yes    1869
Name: count, dtype: int64

In [15]:
df["Churn"].value_counts(normalize=True)*100

Churn
No     73.421502
Yes    26.578498
Name: proportion, dtype: float64

In [17]:
df.groupby("Contract")["Churn"].value_counts(normalize=True) * 100

Contract        Churn
Month-to-month  No       57.290323
                Yes      42.709677
One year        No       88.722826
                Yes      11.277174
Two year        No       97.151335
                Yes       2.848665
Name: proportion, dtype: float64

this correlation shows strong relation where as the cotract is for long time the probability to leave decreases quite strongly

In [18]:
df.groupby("Churn")["tenure"].mean()

Churn
No     37.650010
Yes    17.979133
Name: tenure, dtype: float64

In [17]:
df.groupby("Churn")["MonthlyCharges"].mean()

Churn
No     61.307408
Yes    74.441332
Name: MonthlyCharges, dtype: float64

In [19]:
df.groupby(["Contract", "Churn"])["MonthlyCharges"].mean()

Contract        Churn
Month-to-month  No       61.462635
                Yes      73.019396
One year        No       62.540926
                Yes      85.050904
Two year        No       60.112798
                Yes      86.777083
Name: MonthlyCharges, dtype: float64

In [20]:
df.info()

<class 'pandas.DataFrame'>
Index: 7032 entries, 0 to 7042
Data columns (total 21 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   customerID        7032 non-null   str
 1   gender            7032 non-null   str
 2   SeniorCitizen     7032 non-null   int64
 3   Partner           7032 non-null   str
 4   Dependents        7032 non-null   str
 5   tenure            7032 non-null   int64
 6   PhoneService      7032 non-null   str
 7   MultipleLines     7032 non-null   str
 8   InternetService   7032 non-null   str
 9   OnlineSecurity    7032 non-null   str
 10  OnlineBackup      7032 non-null   str
 11  DeviceProtection  7032 non-null   str
 12  TechSupport       7032 non-null   str
 13  StreamingTV       7032 non-null   str
 14  StreamingMovies   7032 non-null   str
 15  Contract          7032 non-null   str
 16  PaperlessBilling  7032 non-null   str
 17  PaymentMethod     7032 non-null   str
 18  MonthlyCharges    7032 non-null   float64
 19  TotalCharges      7032 non-null   float64
 20  Churn             7032 non-null   str
dtypes: float64(2), int64(2), str(17)
memory usage: 1.2 MB

In [21]:
X = df.drop(columns=["Churn", "customerID"])
y = df["Churn"].map({"No": 0, "Yes": 1})

In [22]:
print("X shape:", X.shape)
print("y shape:", y.shape)
print(y.value_counts())

X shape: (7032, 19)
y shape: (7032,)
Churn
0    5163
1    1869
Name: count, dtype: int64

In [23]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (5625, 19)
X_test: (1407, 19)
y_train: (5625,)
y_test: (1407,)

In [24]:
numerical_features = X_train.select_dtypes(
    include=["int64", "float64"]
).columns.tolist()

categorical_features = X_train.select_dtypes(
    include=["str", "object", "category"]
).columns.tolist()

print("Numerical features:", numerical_features)
print("\nCategorical features:", categorical_features)

Numerical features: ['SeniorCitizen', 'tenure', 'MonthlyCharges', 'TotalCharges']

Categorical features: ['gender', 'Partner', 'Dependents', 'PhoneService', 'MultipleLines', 'InternetService', 'OnlineSecurity', 'OnlineBackup', 'DeviceProtection', 'TechSupport', 'StreamingTV', 'StreamingMovies', 'Contract', 'PaperlessBilling', 'PaymentMethod']

In [25]:

from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

preprocessor = ColumnTransformer(
    transformers=[
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ]
)

In [26]:
X_train_processed = preprocessor.fit_transform(X_train)
X_test_processed = preprocessor.transform(X_test)

print("Training data shape:", X_train_processed.shape)
print("Testing data shape:", X_test_processed.shape)

Training data shape: (5625, 45)
Testing data shape: (1407, 45)

In [27]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

model = LogisticRegression(random_state=42)

model.fit(X_train_processed, y_train)

y_pred = model.predict(X_test_processed)

print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nClassification Report:")
print(classification_report(y_test, y_pred))

Accuracy: 0.8038379530916845

Classification Report:
              precision    recall  f1-score   support

           0       0.85      0.89      0.87      1033
           1       0.65      0.57      0.61       374

    accuracy                           0.80      1407
   macro avg       0.75      0.73      0.74      1407
weighted avg       0.80      0.80      0.80      1407

In [28]:
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report

rf_model = RandomForestClassifier(
    n_estimators=200,
    random_state=42,
    class_weight="balanced"
)

rf_model.fit(X_train_processed, y_train)

rf_pred = rf_model.predict(X_test_processed)

print("Random Forest Accuracy:", accuracy_score(y_test, rf_pred))
print("\nClassification Report:")
print(classification_report(y_test, rf_pred))

Random Forest Accuracy: 0.7839374555792467

Classification Report:
              precision    recall  f1-score   support

           0       0.82      0.90      0.86      1033
           1       0.62      0.47      0.54       374

    accuracy                           0.78      1407
   macro avg       0.72      0.68      0.70      1407
weighted avg       0.77      0.78      0.77      1407

In [29]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import accuracy_score, classification_report

gb_model = GradientBoostingClassifier(random_state=42)

gb_model.fit(X_train_processed, y_train)

gb_pred = gb_model.predict(X_test_processed)

print("Gradient Boosting Accuracy:", accuracy_score(y_test, gb_pred))
print("\nClassification Report:")
print(classification_report(y_test, gb_pred))

Gradient Boosting Accuracy: 0.7960199004975125

Classification Report:
              precision    recall  f1-score   support

           0       0.84      0.89      0.87      1033
           1       0.64      0.53      0.58       374

    accuracy                           0.80      1407
   macro avg       0.74      0.71      0.72      1407
weighted avg       0.79      0.80      0.79      1407

In [30]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score, classification_report

balanced_model = LogisticRegression(
    random_state=42,
    class_weight="balanced"
)

balanced_model.fit(X_train_processed, y_train)

balanced_pred = balanced_model.predict(X_test_processed)

print("Balanced Logistic Regression Accuracy:",
      accuracy_score(y_test, balanced_pred))

print("\nClassification Report:")
print(classification_report(y_test, balanced_pred))

Balanced Logistic Regression Accuracy: 0.7256574271499645

Classification Report:
              precision    recall  f1-score   support

           0       0.90      0.70      0.79      1033
           1       0.49      0.80      0.61       374

    accuracy                           0.73      1407
   macro avg       0.70      0.75      0.70      1407
weighted avg       0.79      0.73      0.74      1407

In [32]:
from sklearn.metrics import classification_report

# Get the probability of each customer churning
y_proba = model.predict_proba(X_test_processed)[:, 1]

# Try a lower threshold
threshold = 0.4

# Predict churn when probability >= 0.35
threshold_pred = (y_proba >= threshold).astype(int)

print(f"Threshold: {threshold}")
print("\nClassification Report:")
print(classification_report(y_test, threshold_pred))

Threshold: 0.4

Classification Report:
              precision    recall  f1-score   support

           0       0.88      0.82      0.85      1033
           1       0.58      0.68      0.63       374

    accuracy                           0.78      1407
   macro avg       0.73      0.75      0.74      1407
weighted avg       0.80      0.78      0.79      1407

In [33]:
import pandas as pd

feature_names = preprocessor.get_feature_names_out()

importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": rf_model.feature_importances_
})

importance_df = importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(importance_df.head(15))

                                Feature  Importance
3                     num__TotalCharges    0.141613
1                           num__tenure    0.130659
2                   num__MonthlyCharges    0.122796
36         cat__Contract_Month-to-month    0.073600
38               cat__Contract_Two year    0.037696
18               cat__OnlineSecurity_No    0.037482
27                  cat__TechSupport_No    0.032245
43  cat__PaymentMethod_Electronic check    0.028836
16     cat__InternetService_Fiber optic    0.027259
21                 cat__OnlineBackup_No    0.017718
4                    cat__gender_Female    0.016419
0                    num__SeniorCitizen    0.016347
5                      cat__gender_Male    0.016123
40            cat__PaperlessBilling_Yes    0.014658
39             cat__PaperlessBilling_No    0.014165

In [34]:
from sklearn.inspection import permutation_importance
import pandas as pd

perm_result = permutation_importance(
    rf_model,
    X_test_processed,
    y_test,
    scoring="f1",
    n_repeats=10,
    random_state=42,
    n_jobs=-1
)

perm_importance_df = pd.DataFrame({
    "Feature": feature_names,
    "Importance": perm_result.importances_mean,
    "Std": perm_result.importances_std
})

perm_importance_df = perm_importance_df.sort_values(
    by="Importance",
    ascending=False
)

print(perm_importance_df.head(15))

                                     Feature  Importance       Std
1                                num__tenure    0.108556  0.021245
36              cat__Contract_Month-to-month    0.098126  0.016433
3                          num__TotalCharges    0.081596  0.017316
2                        num__MonthlyCharges    0.052704  0.012261
16          cat__InternetService_Fiber optic    0.042324  0.012002
18                    cat__OnlineSecurity_No    0.031230  0.012500
27                       cat__TechSupport_No    0.018107  0.010882
38                    cat__Contract_Two year    0.014985  0.009389
15                  cat__InternetService_DSL    0.006576  0.007813
14                    cat__MultipleLines_Yes    0.006307  0.007127
20                   cat__OnlineSecurity_Yes    0.005778  0.004899
34  cat__StreamingMovies_No internet service    0.004561  0.002966
13       cat__MultipleLines_No phone service    0.004236  0.001722
37                    cat__Contract_One year    0.004196  0.005217
10                      cat__PhoneService_No    0.003869  0.001647

In [35]:

from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import StandardScaler, OneHotEncoder

# Split the existing training data into training and validation sets
X_fit, X_val, y_fit, y_val = train_test_split(
    X_train,
    y_train,
    test_size=0.2,
    random_state=42,
    stratify=y_train
)

# Build the complete pipeline
churn_pipeline = Pipeline([
    ("preprocessor", ColumnTransformer([
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ])),
    ("model", LogisticRegression(random_state=42))
])

# Train the pipeline
churn_pipeline.fit(X_fit, y_fit)

print("Training rows:", X_fit.shape[0])
print("Validation rows:", X_val.shape[0])
print("Pipeline trained successfully!")

Training rows: 4500
Validation rows: 1125
Pipeline trained successfully!

In [36]:

from sklearn.metrics import accuracy_score, classification_report

# Predict churn using the default threshold of 0.5
y_val_pred = churn_pipeline.predict(X_val)

print("Validation Accuracy:", accuracy_score(y_val, y_val_pred))
print("\nClassification Report:")
print(classification_report(y_val, y_val_pred))

Validation Accuracy: 0.784

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.88      0.86       826
           1       0.61      0.52      0.56       299

    accuracy                           0.78      1125
   macro avg       0.72      0.70      0.71      1125
weighted avg       0.78      0.78      0.78      1125

In [37]:

from xgboost import XGBClassifier
from sklearn.pipeline import Pipeline
from sklearn.metrics import accuracy_score, classification_report

# Build the XGBoost pipeline
xgb_pipeline = Pipeline([
    ("preprocessor", ColumnTransformer([
        ("num", StandardScaler(), numerical_features),
        ("cat", OneHotEncoder(handle_unknown="ignore"), categorical_features)
    ])),
    ("model", XGBClassifier(
        n_estimators=200,
        max_depth=3,
        learning_rate=0.05,
        subsample=0.8,
        colsample_bytree=0.8,
        eval_metric="logloss",
        random_state=42
    ))
])

# Train on the training portion
xgb_pipeline.fit(X_fit, y_fit)

# Evaluate on validation data
xgb_val_pred = xgb_pipeline.predict(X_val)

print("XGBoost Validation Accuracy:",
      accuracy_score(y_val, xgb_val_pred))

print("\nClassification Report:")
print(classification_report(y_val, xgb_val_pred))

XGBoost Validation Accuracy: 0.7911111111111111

Classification Report:
              precision    recall  f1-score   support

           0       0.83      0.90      0.86       826
           1       0.64      0.48      0.55       299

    accuracy                           0.79      1125
   macro avg       0.74      0.69      0.71      1125
weighted avg       0.78      0.79      0.78      1125

In [38]:

from sklearn.metrics import accuracy_score, classification_report

# Get predicted probabilities for churn
xgb_val_proba = xgb_pipeline.predict_proba(X_val)[:, 1]

# Lower the threshold to 0.40
xgb_threshold = 0.40

# Generate predictions using the new threshold
xgb_val_threshold_pred = (
    xgb_val_proba >= xgb_threshold
).astype(int)

print("XGBoost Threshold:", xgb_threshold)
print("Validation Accuracy:",
      accuracy_score(y_val, xgb_val_threshold_pred))

print("\nClassification Report:")
print(classification_report(y_val, xgb_val_threshold_pred))

XGBoost Threshold: 0.4
Validation Accuracy: 0.7786666666666666

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.84      0.85       826
           1       0.58      0.62      0.60       299

    accuracy                           0.78      1125
   macro avg       0.72      0.73      0.72      1125
weighted avg       0.78      0.78      0.78      1125

In [ ]:

from sklearn.metrics import accuracy_score, classification_report

# Get probabilities of churn from the validation set
val_probabilities = churn_pipeline.predict_proba(X_val)[:, 1]

# Apply  chosen threshold
threshold = 0.40
val_predictions = (val_probabilities >= threshold).astype(int)

print("Threshold:", threshold)
print("Validation Accuracy:", accuracy_score(y_val, val_predictions))
print("\nClassification Report:")
print(classification_report(y_val, val_predictions))

Threshold: 0.4
Validation Accuracy: 0.7795555555555556

Classification Report:
              precision    recall  f1-score   support

           0       0.86      0.83      0.85       826
           1       0.58      0.64      0.61       299

    accuracy                           0.78      1125
   macro avg       0.72      0.73      0.73      1125
weighted avg       0.79      0.78      0.78      1125

In [41]:
import joblib
#finally a saved model
joblib.dump(churn_pipeline, "churn_model.pkl")

print("Model saved successfully!")

Model saved successfully!

In [42]:
#threshold saveddddd
joblib.dump(0.40, "churn_threshold.pkl")

print("Threshold saved successfully!")

Threshold saved successfully!

In [43]:
import joblib

# Loading the saved pipeline and threshold
loaded_model = joblib.load("churn_model.pkl")
loaded_threshold = joblib.load("churn_threshold.pkl")

# Predict the churn probabilities for this data
probabilities = loaded_model.predict_proba(X_val)[:, 1]

# Apply the saved(0.4) threshold
predictions = (probabilities >= loaded_threshold).astype(int)

print("Loaded threshold:", loaded_threshold)
print("\nFirst 10 churn probabilities:")
print(probabilities[:10])

print("\nFirst 10 predictions:")
print(predictions[:10])

Loaded threshold: 0.4

First 10 churn probabilities:
[0.59514725 0.17977246 0.20179841 0.06374914 0.0582167  0.37429954
 0.01167703 0.20603169 0.06809491 0.11275645]

First 10 predictions:
[1 0 0 0 0 0 0 0 0 0]